### ISSUE TITLE
Alterar a rota da tela de login

### ISSUE THREAD

**Issue by apolobra** [smartads-tech/app#4]
Ao acessar https://smartadsv1.herokuapp.com/ 

Se o usuário não tiver logado, redirecionar para o form Logar

**Comment by rogeriosmartads** [comment]
Já alterei o timeout do devise para 2 minutos, ou seja se não houver nenhuma iteração do usuário com o app em 2 minutos será necessário novo login. 
Se o usuário der logout é preciso fazer novo login.
Se o usuário sair da app e retornar antes de 2 minutos o app está permitindo entrar sem login, estou vendo no devise o que é preciso para resolver isso.

**Comment by apolobra** [comment]
É necessário alterar a rota da página de login.
